config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'

  resources :pets do
    resources :chatrooms, only: :create

    collection do
      get :my_pets
    end

    collection do
      get :favorites
    end

    member do
      patch :change_heat
    end

    member do
      patch :make_favorite
    end
  end

  resources :chatrooms, only: %i[index show] do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :user
  belongs_to :owner, class_name: 'User'
  has_many :messages, dependent: :destroy

  validates :user, uniqueness: {scope: :owner}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :sex, :photo, :breed, :pet_type, :address, presence: true

  after_create :set_default

  def set_default
    if self.sex == "male"
      self.on_heat = true
    else
      self.on_heat = false
    end
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :pets, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def after_sign_in_path_for(_resource)
    pets_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name photo])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name photo])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = policy_scope(Chatroom)
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @chatroom = Chatroom.create(user: current_user, owner: @pet.user)
    authorize @chatroom

    redirect_to chatroom_path(@chatroom)
  end

  def show
    @chatroom = Chatroom.find(params[:id])

    @message = Message.new(user: @chatroom.user, chatroom: @chatroom)
    authorize @chatroom
  end

  def my_chatrooms
    @chatrooms = Chatroom.where(user: current_user)
    authorize Chatroom
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    authorize @message
    if @message.save
      redirect_to chatroom_path(@chatroom)
    else
      render "chatrooms/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]

  def index
    session[:last_page] = 'pets_index'
    if !params[:pet1].nil?
      @pets = []
      params.each do |key, value|
        if key.include?("pet")
          @pets << policy_scope(Pet).where(breed: value)
        end
      end
      @pets.flatten!
    else
      @pets = policy_scope(Pet).order(:on_heat, sex: :desc)
    end
      if !params[:pet_type].nil?
        @pets = @pets.select { |pet| pet.pet_type == params[:pet_type] }
      else
        @pets = @pets.select { |pet| pet.pet_type.downcase == "dog" }
      end
  end

  def show
    @chatroom = Chatroom.find_by(user: current_user, owner: @pet.user)
    @marker =
      {
        lat: @pet.latitude,
        lng: @pet.longitude
      }
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    authorize @pet

    if @pet.save
      redirect_to my_pets_pets_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  def my_pets
    @pets = Pet.where(user: current_user)
    authorize Pet
    session[:last_page] = 'my_pets'
  end

  def favorites
    @pets = Pet.where(favorite: true).order(pet_type: :desc, breed: :asc)
    authorize Pet
    session[:last_page] = 'my_pets'
  end

  def change_heat
    set_pet
    if @pet.on_heat
      @pet.update(on_heat: false)
    else
      @pet.update(on_heat: true)
    end
    redirect_to @pet
  end

  def make_favorite
    set_pet
    if @pet.favorite
      @pet.update(favorite: false)
    else
      @pet.update(favorite: true)
    end
    redirect_to @pet
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
    authorize @pet
  end

  def pet_params
    params.require(:pet).permit(:pet_type, :name, :sex, :breed, :birthday, :pedigree_number, :description, :on_heat, :photo, :address, :favorite)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def after_update_path_for(_resource)
    pets_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
  def chat_avatar(chat, user)
    user_avatar = chat.owner
    user_avatar = chat.user if chat.owner == user

    if user_avatar.photo.attached?
      cl_image_tag user_avatar.photo.key, class: "avatar"
    else
      image_tag "avatar.jpg", class: "avatar"
    end
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def avatar_url(user)
    if user.photo.attached?
      cl_image_path user.photo.key
    else
      asset_url "avatar.jpg"
    end
  end
end

app/views/chatrooms/index.html.erb
<div class="container">
  <div class=" mt-5 text-center our-forms show-messages justify-content-center ">
    <div class="d-flex justify-content-center">
      <%= link_to pets_path,
      class: '' do %>
        <i class="fas fa-arrow-left mt-3"></i>
      <% end %>
      <h1 class="mb-3">Messages</h1>
      <div class="width-class"></div>
    </div>

    <div class="mt-5">
      <div class="row">
        <%# <div class="co 12 col"> %>

        <% @chatrooms.each do |chat| %>
          <% if chat.messages != [] %>
          <%= link_to chatroom_path(chat) do %>
          <div class="co-12 colsm-6 col-md-4 mb-3">
            <div class="card-product">
              <div class="avatar-message">
                <%= chat_avatar(chat, current_user) %>
              </div>
              <div class="card-product-infos">
                <% if chat.owner != current_user %>
                  <h2><%= "#{chat.owner.first_name} #{chat.owner.last_name}" %></h2>
                <% else %>
                  <h2><%= "#{chat.user.first_name} #{chat.user.last_name}" %></h2>
                <% end %>
                <p><%= chat.updated_at.to_date %></p>
              </div>
            </div>
          <% end %>
          </div>
        <% end %>
        <% end %>
        <%# </div> %>
      </div>
    </div>
  </div>
</div>

app/views/chatrooms/my_chatrooms.html.erb
<h1>Messages</h1>

<% @chatrooms.each do |chat| %>
  <%= link_to chatroom_path(chat) do %>

  <% if chat.owner.photo.attached? %>
    <%= cl_image_tag chat.owner.photo.key, class: "avatar" %>
  <% else %>
    <%= image_tag "avatar.jpg", class: "avatar" %>
  <% end %>

  <h2><%= "#{chat.owner.first_name} #{chat.owner.last_name}" %></h2>
  <p><%= chat.updated_at.to_date %></p>
  <% end %>
<% end %>

<%= link_to "Back", pets_path %>

app/views/chatrooms/show.html.erb
<div class="container">
  <div class=" mt-5 text-center our-forms justify-content-center ">
    <div class="d-flex justify-content-center">
    <%= link_to pets_path,
    class: '' do %>
      <i class="fas fa-arrow-left mt-1"></i>
    <% end %>
  <h2 class="mb-3">Chatroom</h2>
  <div class="width-class"></div>
  </div>
  </div>
  <div class="row">
    <div class="col-8 offset-2">

    <div class="style"> <%# dont remove this, it will break app %>
      <div class="row"></div>
      <div class="text-center mt-4">
        <% if @chatroom.owner != current_user %>
          <p>Talking with <%= "#{@chatroom.owner.first_name} #{@chatroom.owner.last_name}" %></p>
          <%= cl_image_tag @chatroom.owner.photo.key, class: "avatar-bigger mb-5"%>
        <% else %>
          <p>Talking with <%= "#{@chatroom.user.first_name} #{@chatroom.user.last_name}" %></p>
          <%= cl_image_tag @chatroom.user.photo.key, class: "avatar-bigger mb-5"%>
        <% end %>

      </div>
      <div class="chatroom-container" id="messages" data-chatroom-id="<%= @chatroom.id %>">
        <% @chatroom.messages.each do |message| %>
          <div class="message-container <%= current_user == message.user ? "own" : "" %>" id="message-<%= message.id %>">
            <p class="message-container-content"><%= message.content %></p>
            <i class="author">
              <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
            </i>
          </div>
        <% end %>
      </div>
      <div class="message-box our-forms mt-5">
        <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
          <%= f.input :content, label: false, input_html: {autocomplete: "off" }, placeholder: "Type message" %>
        <% end %>
    </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# Name on navbar %>
    <title>BreedMe</title>

    <%# Meta Tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%# Icon on Navbar %>
    <%# <link rel="shortcut icon" %>
    <%= favicon_link_tag %>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%# Description of site when pasted somewhere %>
    <meta name="description" content="BreedMe is the only pet matching app allows you to pick and match your next purebred mate—and it's free! Join now to start a new pet family!">

    <%# keywords %>
    <meta name="keywords" content="BreedMe, pet matching, app, purebred, pure breed, breed pets, breeders, puppies, kittens" />

    <%# Robots will: %>
    <meta name="robots" content="index,follow" />

    <%# Canonical tag %>
    <link rel="canonical" href="https://www.breedme.app">

    <%# OpenGraph tags %>
    <meta property="og:title" content="BreedMe | Find Pet Breeding Partners!" />
    <meta property="og:url" content="https://www.breedme.app" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="BreedMe is the only pet matching app allows you to pick and match your next purebred mate—and it's free! Join now to start a new pet family!" />
    <%# <meta property="og:image" content="https://"> need help on this one %>
    <meta property="og:locale" content="en_US">


    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%# Jquery %>

    <%# Meta Tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%# Google Font %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;600;700;800;900&display=swap" rel="stylesheet">
    <%# Font Awesome %>
    <script src="https://kit.fontawesome.com/8c434695e5.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# mapbox %>
    <%= stylesheet_pack_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% unless params[:controller] == "pages" || params[:controller].include?("devise") || (params[:controller] == 'registrations' && params[:action] == 'new') %>
      <%= render 'shared/navbar' %>
    <% end %>

    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="change-me">
  <div class="container">
  <%# Header %>
  <div class="header pt-3 mb-5">
    <%= image_tag "breedme_logo.png" %>
    <div class="header-options">
      <h4 class="mr-4 pt-3">Have an account?</h4>
      <% if user_signed_in? %>
        <%= link_to "Sign in", pets_path, class: 'btn btn-color' %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-color" %>
      <% end %>
    </div>
  </div>
  <%# Hero Banner %>
    <div class="row banner">
      <div class="col-md-10">
        <h1 class="mb-4">FIND BREEDING PARTNERS FOR YOUR PETS!</h1>
        <p class="mb-2">BreedMe is the only pet matching app that helps you find what you need.
            You deserve to know your other breeders.
            Meet them today!</p>
        <p class="mt-4">By clicking Join, you agree to our <a class="underline" href="#">Terms</a>. Learn how we process your data in our <a class="underline" href="#">Privacy Policy</a> and <a class="underline" href="#">Cookies Policy</a>.</p>
        <button class="mt-4"><%= link_to "JOIN BREEDME!", new_user_registration_path, class: "nav-link" %></button>
      </div>
      <div class="col-md-2" id="cf">
        <%= image_tag "pet3.png", class:"landing-foto-dog bottom" %>
        <%= image_tag "pet_cat.png", class:"landing-foto-cat top" %>
      </div>
    </div>
  </div>
  <%# Footer %>
  <%# or maybe not %>
</div>

app/views/pets/edit.html.erb
<%= render "form", restaurant: @pet %>

app/views/pets/favorites.html.erb
<div class="container">
  <div class="my-pets">
    <div class=" mt-5 text-center our-forms justify-content-center ">
      <div class="d-flex justify-content-center">
      <%= link_to pets_path,
      class: '' do %>
        <i class="fas fa-arrow-left mt-3"></i>
      <% end %>
    <h1 class="mb-3">Favorites</h1>
    <div class="width-class"></div>
    </div>
    </div>
    <div class="row">
      <% @pets.each do |pet| %>
        <%= link_to pet_path(pet) do %>
        <div class="co-12 colsm-6 col-md-4 mb-3">
          <div class="my-pet-card m-1 mt-3">
            <%= cl_image_tag pet.photo.key%>
            <div class="my-pet-info">
              <div class="pet-text">
                <h2><%= pet.name %></h2>
                <p><%= pet.breed %></p>
              </div>
              <h2 class="my-pet-extrax"><%= pet.sex %></h2>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/my_pets.html.erb
<div class="container">
  <div class="my-pets">
    <div class=" mt-5 text-center our-forms justify-content-center ">
      <div class="d-flex justify-content-center">
      <%= link_to pets_path,
      class: '' do %>
        <i class="fas fa-arrow-left mt-3"></i>
      <% end %>
    <h1 class="mb-3">My pets</h1>
    <div class="width-class"></div>
    </div>
    </div>
    <div class="row">
      <div id="add-pet" class="co-12 colsm-6 col-md-4 mb-3">
        <div class="my-pet-card m-1 mt-3">
        <%= image_tag "avatar.jpg" %>
          <div class="my-pet-info">
            <div class="pet-text">
              <h2>Add a pet!</h2>
              <% if policy(Pet).create? %>
                <%= link_to '+ Add', new_pet_path, id:"add-pet-button" %>
              <% end %>
            </div>
            <h2 class="my-pet-extrax blurry">pet sex</h2>
          </div>
        </div>
      </div>
      <% @pets.reverse.each do |pet| %>
        <%= link_to pet_path(pet) do %>
        <div class="co-12 colsm-6 col-md-4 mb-3">
          <div class="my-pet-card m-1 mt-3">
            <%= cl_image_tag pet.photo.key%>
            <div class="my-pet-info">
              <div class="pet-text">
                <div class='d-flex'>
                  <h2 class="mr-2"><%= pet.name %></h2>
                    <% if pet.pedigree_number %>
                      <div data-tooltip="has a pedigree number" class="d-flex">
                        <i class="fas fa-check-circle super_tooltip mr-2"></i>
                      </div>
                    <% end %>
                    <%# flame symbol if female on heat %>
                    <% if pet.sex == 'female' && pet.on_heat == true %>
                      <div data-tooltip="female on heat" class="d-flex">
                        <i class="fas fa-fire-alt super_tooltip"></i>
                      </div>
                    <% end %>
                </div>
                <p><%= pet.breed %></p>
              </div>
              <h2 class="my-pet-extrax"><%= pet.sex %></h2>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/new.html.erb
<%= render "form", restaurant: @pet %>

app/views/pets/show.html.erb
<% content_for :meta_title, "#{@pet.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @pet.description %>
<% content_for :meta_image, cl_image_path(@pet.photo) %>

<div class="container petinfo p-5">
  <div class="our-forms m-2">
    <div class="d-flex">
      <% if session[:last_page] == 'my_pets' %>
        <%= link_to my_pets_pets_path do %>
          <i class="fas fa-arrow-left mr-0 m-1"></i>
        <% end %>
        <div class="icons_edit_delete pt-1 pl-1">
          <% if policy(@pet).edit? %>
            <%= link_to edit_pet_path(@pet) do %>
              <i class="fas fa-edit mr-0 m-1"></i>
            <% end %>
          <% end %>
          <% if policy(@pet).destroy? %>
            <%= link_to pet_path(@pet), method: :delete do %>
              <i class="fas fa-trash-alt mr-0 m-1"></i>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row text-center">
    <div class="avatar-dog right-col col-md-4">
      <%= cl_image_tag @pet.photo.key %>
      <div class="col right-col-info ">
        <ul class="list-unstyled text-left ml-3">
          <li class="pb-3"><i class="fas fa-venus-mars"></i>:         <%= @pet.sex.capitalize %></li>
          <% if @pet.birthday %>
            <li class="pb-3"><i class="far fa-calendar-alt"></i>:       <%= @pet.birthday %></li>
          <% end %>
          <% if @pet.pedigree_number %>
            <li class="pb-3"><i class="fas fa-list-ol"></i>:       <%= @pet.pedigree_number %></li>
          <% end %>
        </ul>
        <% if @pet.user != current_user %>
          <button class="btn-ours mt-4 mb-5">
            <% if @chatroom.present?  %>
              <%= link_to "Message Owner", chatroom_path(@chatroom.id) %>
            <% else %>
              <%= link_to "Message Owner", pet_chatrooms_path(@pet), method: :post %>
            <% end %>
          </button>
        <% else %>
          <h4><strong>You are this pet's owner</strong></h4>
        <% end %>

        <%# button heat on/off %>
        <% if @pet.sex == 'female' && @pet.user == current_user %>
        <% @pet.on_heat ? text = "Turn Off Heat" : text = "Turn On Heat"  %>
        <%= link_to change_heat_pet_path(@pet), method: :patch  do%>
          <button class='btn-ours mb-5'><%= text %></button>
        <% end %>
        <% end %>

        <%# button favorite %>
        <% if @pet.user != current_user %>
        <% @pet.favorite ? text = "Remove from Favorites" : text = "Add to Favorites"  %>
        <%= link_to make_favorite_pet_path(@pet), method: :patch do %>
          <button class='btn-ours mb-5'><%= text %></button>
        <% end %>
        <% end %>

      </div>
    </div>
    <div class="col-md-8 left-col ">
      <h1><%= @pet.name.capitalize  %></h1>
      <h2><%= @pet.breed.capitalize %></h2>
      <div class="text-justify mt-5 mb-5">
        <p><strong>Description: </strong><%= @pet.description %></p>
      </div>
      <div class="col-md-12" id="map"
        style="width: 100%; height: 300px; border-radius:4px;"
        data-markers="<%= @marker.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to pets_path, class: "navbar-brand" do %>
    <%= image_tag "breedme_logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <div class="navbar-light">
          <div class="navbar-nav p-2">
            <%= link_to "Home", pets_path, class: "dropdown-item" %>
            <%= link_to "Favorites", favorites_pets_path, class: "dropdown-item" %>
            <%= link_to "Messages", chatrooms_path, class: "dropdown-item" %>
            <%= link_to "My Pets", my_pets_pets_path, class: "dropdown-item" %>
            <%= link_to "My Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%# avatar na navbar %>
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", height:200, width: 200, crop:"thumb" %>
            <% else %>
              <%= image_tag "avatar.jpg", class: "avatar" %>
            <% end %>
            <%# .. %>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</div>